name: Check Markdown links

on:
  pull_request: # Required for workflows to be able to be approved from forks
  merge_group:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
