name: Wiki Sync

on:
  workflow_dispatch:

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest

    if: github.event_name != 'gollum'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Rebase on Wiki
        run: |
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          # mkdir $TMPDIR
          # cd $TMPDIR
          # git clone 
          # git remote add wiki "https://$WIKI_SYNC_GITHUB_TOKENgithub.com/input-output-hk/cardano-node.wiki.git"
          # git fetch wiki
          # git rebase wiki/main
          # git push origin/main
          # )
